server:
  port: 8082

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

toby:
  auth:
    token:
      sign-key: signKey012345678901234567890123456789
      valid-time: 3600
  otp:
    valid-time: 180

