spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toby
    username: root
    password: M9p19MRqkz1z
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    server: localhost:29092
    mail-group-id: mail_group
    verify-email: verify-email
    verify-email-success: verify-email-success
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: mhoangduc0812@gmail.com
    password: ggwk rasm yywm yeqb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true